name: 'Test output of scheduling code'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate_output:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/PtM-Scheduling'] }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
      
      - name: Test with pytest
        run: pytest --v
  
